# Generated by Django 4.2.4 on 2023-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
