# Generated by Django 4.2.4 on 2023-08-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_messagechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100)),
                ('room_chat', models.CharField(max_length=100)),
                ('rname', models.ForeignKey(blank=True, db_column='Room_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatapp.room')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatapp.signin')),
            ],
        ),
    ]
