# Generated by Django 4.2.4 on 2023-08-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chat_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messagechat',
        ),
    ]
