# Generated by Django 4.2.4 on 2023-08-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_delete_messagechat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat_room',
            new_name='chatroom',
        ),
    ]
